// Generated by build.py. Edit content/ and re-run build.py instead of editing this file.
const SITE_NAME = "Dealloft";
const SHOW_SAMPLES = false;
const CATS = [
 {
  "id": "fashion",
  "name": "Fashion & Beauty",
  "color": "#C4552D"
 },
 {
  "id": "home",
  "name": "Home & Living",
  "color": "#2F4A3A"
 },
 {
  "id": "wellness",
  "name": "Health & Wellness",
  "color": "#8A5A44"
 },
 {
  "id": "tech",
  "name": "Tech & Gadgets",
  "color": "#3C4F76"
 },
 {
  "id": "family",
  "name": "Baby, Kids & Pets",
  "color": "#B9852E"
 },
 {
  "id": "fitness",
  "name": "Fitness & Outdoors",
  "color": "#5B6B3A"
 }
];
const BRANDS = {
 "retroid": {
  "name": "Retroid",
  "url": "https://www.goretroid.com/",
  "aff": "https://www.goretroid.com?sca_ref=9889864.sESDYDakkk",
  "aff2": ""
 },
 "kinglou": {
  "name": "King Lou Pets",
  "url": "https://kingloupets.com/",
  "aff": "https://kingloupets.com?sca_ref=10062305.4Dtw8FxTnXNB9yp4",
  "aff2": "https://kingloupets.com/10062305"
 },
 "peekaboo": {
  "name": "Peekaboo Pillow",
  "url": "https://peekaboopillow.com/",
  "aff": "",
  "aff2": ""
 },
 "andover": {
  "name": "Andover Audio",
  "url": "https://www.andoveraudio.com/",
  "aff": "",
  "aff2": ""
 }
};
const DEALS = [
 {
  "brand": "kinglou",
  "cat": "family",
  "offer": "Free shipping on orders of $60 or more. Treats start at about $25. Code from our partnership; any discount shows at checkout.",
  "code": "TOMSP27",
  "checked": "2026-10-03"
 },
 {
  "brand": "andover",
  "cat": "tech",
  "offer": "60-day in-home trial and free shipping on orders of $100 or more.",
  "code": "",
  "checked": "2026-10-03"
 },
 {
  "brand": "peekaboo",
  "cat": "family",
  "offer": "Original listed at $139 (was $169). Plush listed at $119 (was $149).",
  "code": "",
  "checked": "2026-10-03"
 },
 {
  "brand": "retroid",
  "cat": "tech",
  "offer": "Pocket 5 listed at $179 (was $209); Pocket Classic at $99 (was $149). Showed as sold out when checked.",
  "code": "",
  "checked": "2026-10-03"
 }
];
const POSTS = [
 {
  "slug": "andover-audio-spinbase-2-guide",
  "title": "Andover Audio SpinBase 2: Specs, Price and Who This Turntable Speaker Is For",
  "excerpt": "Specs, price, inputs and trial terms for the Andover SpinBase 2, and who a turntable speaker base suits.",
  "cat": "tech",
  "date": "2026-10-03",
  "read": "6 min read",
  "href": "posts/andover-audio-spinbase-2-guide.html"
 },
 {
  "slug": "king-lou-pets-treats-guide",
  "title": "King Lou Pets Treats: What's Inside, What They Cost and How to Handle Raw Dog Treats Safely",
  "excerpt": "What King Lou Pets sells, what the brand claims, what it costs, and what the FDA says about handling raw pet food.",
  "cat": "family",
  "date": "2026-10-03",
  "read": "6 min read",
  "href": "posts/king-lou-pets-treats-guide.html"
 },
 {
  "slug": "peekaboo-pillow-guide",
  "title": "Peekaboo Pillow Guide: Sizes, Price and Safety Notes Before You Buy",
  "excerpt": "What the Peekaboo Pillow is, how much it costs, what it is made of, and why it should never be used for sleep.",
  "cat": "family",
  "date": "2026-10-03",
  "read": "6 min read",
  "href": "posts/peekaboo-pillow-guide.html"
 },
 {
  "slug": "retroid-pocket-guide-2026",
  "title": "Which Retroid Pocket Should You Buy in 2026? Pocket 6 vs Pocket 5 vs Nova vs Classic",
  "excerpt": "A plain-English comparison of the Retroid Pocket 6, Pocket 5, Nova and Classic, with current store prices and what each is best for.",
  "cat": "tech",
  "date": "2026-10-03",
  "read": "7 min read",
  "href": "posts/retroid-pocket-guide-2026.html"
 }
];
